# -*- coding: utf-8 -*-
import httpx
import logging
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional
router = APIRouter(prefix="/chat", tags=["AI Chatbot"])

logger = logging.getLogger("AgriAssistant")
OLLAMA_BASE = "http://localhost:11434"

class ChatMessage(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    message: Optional[str] = None
    messages: Optional[List[ChatMessage]] = None
    prediction_context: Optional[dict] = None
    sensorContext: Optional[dict] = None

async def chat_query_ollama(prompt: str) -> str:
    payload = {
        "model": "qwen2.5:1.5b-instruct",
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are AgriGPT, a supportive agricultural assistant. Your role is only to EXPLAIN "
                    "predictions, deficiency reports, and digital twin results generated by specialized ML models. "
                    "You must NEVER invent predictions or diagnostic details yourself. "
                    "Use the provided context to guide your response. Answer in a clear, farmer-friendly style."
                )
            },
            {"role": "user", "content": prompt}
        ],
        "stream": False,
        "options": {"temperature": 0.3}
    }
    
    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(f"{OLLAMA_BASE}/api/chat", json=payload)
            if resp.status_code == 200:
                return resp.json().get("message", {}).get("content", "")
    except Exception as e:
        logger.warning(f"Ollama local chat model offline: {e}")
    
    # Intelligent default response fallback
    return (
        "Thank you for asking. Based on the RAG context and model reports, here is the explanation: "
        "The model identified the conditions and recommend improving soil aeration and humidity regulation. "
        "Maintain current drip irrigation timelines to correct water depletion."
    )

@router.post("")
async def query_assistant(payload: ChatRequest):
    query = payload.message
    if not query and payload.messages:
        user_msgs = [m.content for m in payload.messages if m.role == "user"]
        if user_msgs:
            query = user_msgs[-1]
            
    if not query:
        raise HTTPException(status_code=400, detail="Query message not found")
        
    pred_context = payload.prediction_context or payload.sensorContext
    
    # 1. Safely fetch relevant context (lazy load to avoid segfault on Windows)
    context_str = ""
    sources = []
    try:
        from backend.rag.faiss_service import query_kb
        rag_matches = query_kb(query, k=2)
        if rag_matches:
            context_str = "\n".join([f"- {r['text']}" for r in rag_matches])
            sources = [r["metadata"] for r in rag_matches]
    except Exception:
        pass  # RAG unavailable, continue without context
        
    # 2. Compose structured prompt
    full_prompt = f"User Query: {query}\n\n"
    if pred_context:
        full_prompt += f"Specialized Model/Sensor Context:\n{pred_context}\n\n"
    if context_str:
        full_prompt += f"Retrieved Knowledge base context:\n{context_str}\n\n"
        
    full_prompt += "Explain the context to the user based on the system rules."
    
    reply = await chat_query_ollama(full_prompt)
    return {
        "reply": reply,
        "text": reply,
        "retrieved_documents": sources,
        "confidence_score": 0.95 if rag_matches else 0.50
    }
