"""
Add cultivation guides for first 10 crops (Batch 1)
Crops: apple, banana, barley, beans, beetroot, broccoli, cauliflower, chickpeas, chili, cotton
"""

import json
import os

# Load existing chatbot_qa_pairs.json
json_path = "agrisense_app/backend/chatbot_qa_pairs.json"

with open(json_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

# Crop guides for Batch 1
new_guides = [
    "🍎 **Apple Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 12-24°C (optimal 15-20°C)\r\n• Cool temperate climate\r\n• Requires 1000-1500 chilling hours (below 7°C)\r\n• Grows well in hills 1500-2700m altitude\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy to sandy loam soil\r\n• pH: 5.5-6.5 (slightly acidic)\r\n• Deep soil (1-2m) for root development\r\n• Good organic matter content\r\n\r\n**Water Management:**\r\n• Regular irrigation during fruit development\r\n• Critical during flowering and fruit set\r\n• Drip irrigation recommended\r\n• Avoid waterlogging\r\n• Total water: 800-1200mm annually\r\n\r\n**Planting Details:**\r\n• Season: December-February (dormant period)\r\n• Spacing: 4-6m between plants (dwarf), 8-10m (standard)\r\n• Planting depth: Same as nursery level\r\n• Grafted plants preferred\r\n• Start bearing: 3-4 years\r\n\r\n**Fertilizer (per tree per year):**\r\n• Nitrogen: 500-800g\r\n• Phosphorus: 200-400g\r\n• Potassium: 600-900g\r\n• Apply FYM 40-50 kg per tree\r\n• Split application recommended\r\n\r\n**Best Practices:**\r\n✓ Regular pruning and training essential\r\n✓ Thinning of fruits for better quality\r\n✓ Control scab, powdery mildew, fire blight\r\n✓ Watch for codling moth, aphids\r\n✓ Harvest at proper maturity based on variety\r\n✓ Handle carefully to avoid bruising\r\n\r\n**Expected Yield:** 15-25 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Sunburn: excessive sun exposure\r\n• Bitter pit: calcium deficiency\r\n• Alternate bearing: improper thinning",
    
    "🍌 **Banana Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 20-35°C (optimal 27°C)\r\n• Tropical and subtropical climate\r\n• High humidity preferred (75-85%)\r\n• Frost sensitive\r\n\r\n**Soil Requirements:**\r\n• Well-drained deep loamy soil\r\n• pH: 6.0-7.5 (ideal 6.5)\r\n• Rich in organic matter\r\n• Good drainage essential\r\n\r\n**Water Management:**\r\n• High water requirement throughout\r\n• Drip irrigation highly recommended\r\n• Critical during flowering and fruit development\r\n• Mulching conserves moisture\r\n• Total water: 1500-2500mm annually\r\n\r\n**Planting Details:**\r\n• Season: Throughout year (avoid extremes)\r\n• Spacing: 1.8-2.5m between plants\r\n• Planting depth: 50-60cm pits\r\n• Use disease-free suckers\r\n• Harvest: 11-14 months after planting\r\n\r\n**Fertilizer (per hectare per year):**\r\n• Nitrogen: 200-300 kg\r\n• Phosphorus: 60-90 kg\r\n• Potassium: 300-400 kg\r\n• Apply FYM 25-30 tonnes\r\n• Split into 6-8 applications\r\n\r\n**Best Practices:**\r\n✓ Desuckering - maintain 1-2 followers\r\n✓ Denavelling to prevent pest infestation\r\n✓ Propping for tall varieties\r\n✓ Control Panama wilt, sigatoka\r\n✓ Watch for banana weevil, nematodes\r\n✓ Harvest at 75-80% maturity\r\n✓ Handle bunches carefully\r\n\r\n**Expected Yield:** 40-60 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Panama wilt: soil-borne fungus\r\n• Bunchy top: viral disease\r\n• Wind damage: inadequate propping",
    
    "🌾 **Barley Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 12-20°C (optimal 15-18°C)\r\n• Cool season cereal\r\n• Tolerates cold better than wheat\r\n• Can withstand light frost\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy to clay loam soil\r\n• pH: 6.0-7.5 (neutral preferred)\r\n• Moderate fertility required\r\n• Salt tolerant compared to other cereals\r\n\r\n**Water Management:**\r\n• 3-5 irrigations typically needed\r\n• Critical at CRI, tillering, flowering, grain filling\r\n• More drought tolerant than wheat\r\n• Total water: 400-550mm\r\n\r\n**Planting Details:**\r\n• Season: Rabi (October-November)\r\n• Seed rate: 100-125 kg/hectare\r\n• Spacing: 20-25cm between rows\r\n• Depth: 5-7cm\r\n• Growing period: 110-140 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 60-80 kg\r\n• Phosphorus: 40-50 kg\r\n• Potassium: 30-40 kg\r\n• Apply full P&K at sowing\r\n• Nitrogen in 2 splits\r\n\r\n**Best Practices:**\r\n✓ Use certified disease-free seeds\r\n✓ Timely sowing crucial for good yields\r\n✓ Line sowing preferred over broadcasting\r\n✓ Control leaf rust, stripe rust, smuts\r\n✓ Watch for aphids, shoot fly\r\n✓ Harvest at full maturity\r\n✓ Thresh and dry properly\r\n\r\n**Expected Yield:** 35-45 quintals/hectare\r\n\r\n**Common Issues:**\r\n• Lodging: excess nitrogen application\r\n• Rusts: humid weather conditions\r\n• Poor germination: deep sowing",
    
    "🫘 **Beans Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 15-25°C (optimal 20-22°C)\r\n• Cool season crop (frost sensitive)\r\n• Warm days and cool nights ideal\r\n• Avoid extreme heat\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy soil\r\n• pH: 6.0-7.0 (neutral preferred)\r\n• Good organic matter content\r\n• Avoid waterlogged conditions\r\n\r\n**Water Management:**\r\n• Regular but moderate watering\r\n• Critical during flowering and pod formation\r\n• Avoid overhead irrigation during flowering\r\n• Drip irrigation recommended\r\n• Total water: 400-600mm\r\n\r\n**Planting Details:**\r\n• Season: Rabi and Spring (October-March)\r\n• Seed rate: 80-100 kg/hectare (bush), 25-30 kg/hectare (pole)\r\n• Spacing: 45cm rows, 10-15cm plants (bush)\r\n• Depth: 3-5cm\r\n• Growing period: 60-90 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 20-30 kg (nitrogen-fixing)\r\n• Phosphorus: 50-60 kg\r\n• Potassium: 40-50 kg\r\n• Apply FYM 15-20 tonnes/hectare\r\n• Rhizobium inoculation beneficial\r\n\r\n**Best Practices:**\r\n✓ Use disease-free certified seeds\r\n✓ Provide support for pole varieties\r\n✓ Regular picking encourages more pods\r\n✓ Control anthracnose, rust, bacterial blight\r\n✓ Watch for aphids, pod borers\r\n✓ Harvest tender pods regularly\r\n✓ Handle carefully to avoid damage\r\n\r\n**Expected Yield:** 8-12 tonnes/hectare (green pods)\r\n\r\n**Common Issues:**\r\n• Pod drop: water stress, high temperature\r\n• Poor pod set: extreme temperatures\r\n• Rust: humid conditions",
    
    "🥕 **Beetroot Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 15-25°C (optimal 18-20°C)\r\n• Cool season crop\r\n• Tolerates light frost\r\n• Prefers moderate climate\r\n\r\n**Soil Requirements:**\r\n• Deep, well-drained loamy soil\r\n• pH: 6.0-7.5 (neutral preferred)\r\n• Rich in organic matter\r\n• Avoid heavy clay and stony soils\r\n\r\n**Water Management:**\r\n• Regular, consistent moisture required\r\n• Critical during root development\r\n• Avoid water stress and waterlogging\r\n• Drip irrigation ideal\r\n• Total water: 400-500mm\r\n\r\n**Planting Details:**\r\n• Season: Rabi and Spring (October-February)\r\n• Seed rate: 8-10 kg/hectare\r\n• Spacing: 30-45cm rows, 10-15cm plants\r\n• Depth: 2-3cm\r\n• Growing period: 60-90 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 80-100 kg\r\n• Phosphorus: 50-60 kg\r\n• Potassium: 60-80 kg\r\n• Apply FYM 20-25 tonnes/hectare\r\n• Boron 10 kg/hectare if deficient\r\n\r\n**Best Practices:**\r\n✓ Prepare fine seedbed\r\n✓ Thin seedlings to proper spacing\r\n✓ Weed control in early stages critical\r\n✓ Control cercospora leaf spot\r\n✓ Watch for aphids, leaf miners\r\n✓ Harvest when roots reach 5-7cm diameter\r\n✓ Store in cool, humid conditions\r\n\r\n**Expected Yield:** 20-30 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Zoning (white rings): irregular watering\r\n• Bolting: exposure to cold temperatures\r\n• Forked roots: hard soil, excess nitrogen",
    
    "🥦 **Broccoli Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 15-22°C (optimal 18-20°C)\r\n• Cool season crop\r\n• Tolerates light frost\r\n• Head formation best in cool weather\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy soil\r\n• pH: 6.0-7.0 (ideal 6.5)\r\n• High organic matter and fertility\r\n• Good moisture retention\r\n\r\n**Water Management:**\r\n• Regular, consistent watering essential\r\n• Critical during head formation\r\n• Maintain even soil moisture\r\n• Drip irrigation recommended\r\n• Total water: 600-750mm\r\n\r\n**Planting Details:**\r\n• Season: Rabi (September-November)\r\n• Nursery: 25-30 day old seedlings\r\n• Spacing: 45-60cm rows, 45cm plants\r\n• Transplanting depth: Up to first leaves\r\n• Growing period: 90-120 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 120-150 kg\r\n• Phosphorus: 60-80 kg\r\n• Potassium: 60-80 kg\r\n• Apply FYM 25-30 tonnes/hectare\r\n• Nitrogen in 3 splits\r\n\r\n**Best Practices:**\r\n✓ Use quality transplants\r\n✓ Maintain consistent moisture\r\n✓ Side-dress nitrogen during growth\r\n✓ Control downy mildew, black rot\r\n✓ Watch for diamond back moth, aphids\r\n✓ Harvest when heads are compact, before flowering\r\n✓ Cut with 15cm stem attached\r\n\r\n**Expected Yield:** 12-18 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Buttoning: stress during early growth\r\n• Hollow stem: boron deficiency, rapid growth\r\n• Premature flowering: temperature stress",
    
    "🥦 **Cauliflower Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 15-22°C (optimal 18-20°C)\r\n• Cool season crop\r\n• Sensitive to frost and heat\r\n• Curd formation needs cool weather\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy to clay loam soil\r\n• pH: 6.0-7.0 (ideal 6.5)\r\n• High fertility and organic matter\r\n• Good moisture retention\r\n\r\n**Water Management:**\r\n• Heavy water requirement\r\n• Critical during curd formation\r\n• Maintain consistent soil moisture\r\n• Drip irrigation ideal\r\n• Total water: 600-800mm\r\n\r\n**Planting Details:**\r\n• Season: Rabi (September-December)\r\n• Nursery: 25-35 day old seedlings\r\n• Spacing: 45-60cm rows, 45-60cm plants\r\n• Transplanting depth: Up to cotyledon leaves\r\n• Growing period: 90-150 days (variety dependent)\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 150-200 kg\r\n• Phosphorus: 60-80 kg\r\n• Potassium: 80-100 kg\r\n• Apply FYM 30-40 tonnes/hectare\r\n• Nitrogen in 3-4 splits\r\n\r\n**Best Practices:**\r\n✓ Use variety suitable for season\r\n✓ Blanching (tying leaves) for white curds\r\n✓ Maintain high soil fertility\r\n✓ Control black rot, downy mildew\r\n✓ Watch for diamond back moth, aphids\r\n✓ Harvest when curds are compact, 15-20cm\r\n✓ Cut with protecting leaves\r\n\r\n**Expected Yield:** 20-30 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Buttoning: early stress, poor nutrition\r\n• Riciness: over-maturity, high temperature\r\n• Discoloration: sun exposure",
    
    "🫘 **Chickpeas Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 20-30°C (optimal 25-28°C)\r\n• Cool, dry climate preferred\r\n• Tolerates light frost at vegetative stage\r\n• Warm weather needed for flowering\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy to clay loam soil\r\n• pH: 6.0-8.0 (wide range tolerance)\r\n• Moderate fertility adequate\r\n• Avoid waterlogged and saline soils\r\n\r\n**Water Management:**\r\n• Drought tolerant but responds to irrigation\r\n• Critical at flowering and pod formation\r\n• 1-2 irrigations sufficient in most areas\r\n• Total water: 350-450mm\r\n\r\n**Planting Details:**\r\n• Season: Rabi (October-November)\r\n• Seed rate: 60-80 kg/hectare\r\n• Spacing: 30-45cm rows, 10cm plants\r\n• Depth: 5-8cm\r\n• Growing period: 100-130 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 20-25 kg (nitrogen-fixing)\r\n• Phosphorus: 40-60 kg\r\n• Potassium: 20-30 kg\r\n• Rhizobium inoculation recommended\r\n• Sulfur 20-30 kg if deficient\r\n\r\n**Best Practices:**\r\n✓ Use certified disease-free seeds\r\n✓ Treat seeds with fungicide and Rhizobium\r\n✓ Timely sowing crucial\r\n✓ Control wilt, blight, pod borer\r\n✓ Watch for gram pod borer, aphids\r\n✓ Harvest when 80% pods turn brown\r\n✓ Dry properly before storage\r\n\r\n**Expected Yield:** 15-25 quintals/hectare\r\n\r\n**Common Issues:**\r\n• Wilt: soil-borne fungus in warm, moist conditions\r\n• Pod borer: major pest, needs monitoring\r\n• Poor nodulation: unsuitable soil conditions",
    
    "🌶️ **Chili Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 20-30°C (optimal 25-28°C)\r\n• Warm season crop\r\n• Requires full sunlight\r\n• Frost sensitive\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy to sandy loam soil\r\n• pH: 6.0-7.0 (ideal 6.5)\r\n• Rich in organic matter\r\n• Good drainage essential\r\n\r\n**Water Management:**\r\n• Regular irrigation required\r\n• Critical at flowering and fruiting\r\n• Avoid waterlogging (causes wilt)\r\n• Drip irrigation highly recommended\r\n• Total water: 600-800mm\r\n\r\n**Planting Details:**\r\n• Season: Kharif, Rabi, Summer\r\n• Nursery: 35-40 day old seedlings\r\n• Spacing: 60-75cm rows, 45-60cm plants\r\n• Transplanting depth: Root ball level\r\n• Growing period: 150-180 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 100-150 kg\r\n• Phosphorus: 50-75 kg\r\n• Potassium: 50-75 kg\r\n• Apply FYM 20-25 tonnes/hectare\r\n• Nitrogen in 3-4 splits\r\n\r\n**Best Practices:**\r\n✓ Use disease-resistant hybrid varieties\r\n✓ Raised bed cultivation in heavy soils\r\n✓ Mulching conserves moisture\r\n✓ Control die-back, anthracnose, wilt\r\n✓ Watch for thrips, mites, fruit borers\r\n✓ Multiple pickings increase yield\r\n✓ Harvest at desired maturity (green/red)\r\n\r\n**Expected Yield:** 10-15 tonnes/hectare (green), 2-3 tonnes/hectare (dry)\r\n\r\n**Common Issues:**\r\n• Wilt: waterlogging, soil-borne pathogens\r\n• Fruit drop: high temperature, water stress\r\n• Sunscald: excessive sun on fruits",
    
    "🌱 **Cotton Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 21-30°C (optimal 25-27°C)\r\n• Warm season crop\r\n• Requires 180-200 frost-free days\r\n• Full sunlight essential\r\n\r\n**Soil Requirements:**\r\n• Deep, well-drained alluvial or black soil\r\n• pH: 6.0-8.0 (wide tolerance)\r\n• Good moisture retention capacity\r\n• Moderate to high fertility\r\n\r\n**Water Management:**\r\n• Critical at flowering and boll development\r\n• 6-10 irrigations typically needed\r\n• Avoid waterlogging\r\n• Total water: 600-1000mm\r\n• Drip irrigation beneficial\r\n\r\n**Planting Details:**\r\n• Season: Kharif (April-June)\r\n• Seed rate: 12-15 kg/hectare (Bt), 20-25 kg/hectare (hybrid)\r\n• Spacing: 60-90cm rows, 45-60cm plants\r\n• Depth: 3-5cm\r\n• Growing period: 150-180 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 120-150 kg\r\n• Phosphorus: 60-80 kg\r\n• Potassium: 60-80 kg\r\n• Apply in 2-3 splits\r\n• Micronutrients based on soil test\r\n\r\n**Best Practices:**\r\n✓ Use Bt hybrid varieties for pest control\r\n✓ Intercropping with pulses/vegetables\r\n✓ Regular monitoring for pests\r\n✓ Control wilt, boll rot, leaf curl\r\n✓ Watch for bollworms, whitefly, aphids\r\n✓ Harvest when bolls fully open\r\n✓ Multiple pickings ensure quality\r\n\r\n**Expected Yield:** 20-30 quintals/hectare (lint)\r\n\r\n**Common Issues:**\r\n• Boll shedding: water stress, pest attack\r\n• Wilting: root rot, nematodes\r\n• Leaf reddening: potassium deficiency"
]

# Add new guides to the answers array
print(f"Current number of answers: {len(data['answers'])}")
data['answers'].extend(new_guides)
print(f"After adding Batch 1: {len(data['answers'])} answers")

# Add corresponding sources
for _ in range(len(new_guides)):
    data['sources'].append("AgriGuide")

# Save updated JSON
with open(json_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("✅ Batch 1 complete! Added guides for:")
print("   1. Apple")
print("   2. Banana")
print("   3. Barley")
print("   4. Beans")
print("   5. Beetroot")
print("   6. Broccoli")
print("   7. Cauliflower")
print("   8. Chickpeas")
print("   9. Chili")
print("  10. Cotton")
