"""
Add cultivation guides for Batch 2 (10 crops)
Crops: cucumber, eggplant, garlic, ginger, grapes, groundnut, guava, lentils, lettuce, mango
"""

import json

# Load existing chatbot_qa_pairs.json
json_path = "agrisense_app/backend/chatbot_qa_pairs.json"

with open(json_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

# Crop guides for Batch 2
new_guides = [
    "🥒 **Cucumber Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 18-30°C (optimal 24-27°C)\r\n• Warm season crop\r\n• Requires full sunlight\r\n• Frost sensitive\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy to sandy loam soil\r\n• pH: 6.0-7.0 (ideal 6.5)\r\n• Rich in organic matter\r\n• Good drainage essential\r\n\r\n**Water Management:**\r\n• Regular, consistent watering essential\r\n• Critical during flowering and fruiting\r\n• Drip irrigation highly recommended\r\n• Avoid water stress (causes bitterness)\r\n• Total water: 500-700mm\r\n\r\n**Planting Details:**\r\n• Season: Summer, Kharif, Spring\r\n• Seed rate: 3-4 kg/hectare (direct), 1.5-2 kg/hectare (transplant)\r\n• Spacing: 1.5-2m rows, 60cm plants\r\n• Depth: 2-3cm\r\n• Growing period: 50-70 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 100-120 kg\r\n• Phosphorus: 50-60 kg\r\n• Potassium: 50-60 kg\r\n• Apply FYM 20-25 tonnes/hectare\r\n• Nitrogen in 3 splits\r\n\r\n**Best Practices:**\r\n✓ Use hybrid disease-resistant varieties\r\n✓ Vertical training improves yield and quality\r\n✓ Regular harvesting encourages more fruits\r\n✓ Control downy mildew, powdery mildew, anthracnose\r\n✓ Watch for fruit fly, aphids, red spider mites\r\n✓ Harvest tender fruits regularly\r\n✓ Morning harvest preferred\r\n\r\n**Expected Yield:** 15-25 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Bitterness: water stress, high temperature\r\n• Fruit drop: poor pollination, nutrient deficiency\r\n• Yellow fruits: over-maturity",
    
    "🍆 **Eggplant (Brinjal) Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 20-30°C (optimal 25-28°C)\r\n• Warm season crop\r\n• Requires full sunlight (6-8 hours)\r\n• Frost sensitive\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy to clay loam soil\r\n• pH: 6.0-7.0 (ideal 6.5)\r\n• Rich in organic matter\r\n• Good drainage important\r\n\r\n**Water Management:**\r\n• Regular irrigation required\r\n• Critical during flowering and fruiting\r\n• Drip irrigation recommended\r\n• Avoid waterlogging\r\n• Total water: 600-800mm\r\n\r\n**Planting Details:**\r\n• Season: Kharif, Rabi, Summer\r\n• Nursery: 30-35 day old seedlings\r\n• Spacing: 60-75cm rows, 45-60cm plants\r\n• Transplanting depth: Root ball level\r\n• Growing period: 120-150 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 100-150 kg\r\n• Phosphorus: 50-75 kg\r\n• Potassium: 50-75 kg\r\n• Apply FYM 20-25 tonnes/hectare\r\n• Nitrogen in 3-4 splits\r\n\r\n**Best Practices:**\r\n✓ Use disease-resistant hybrid varieties\r\n✓ Remove and destroy wilted plants immediately\r\n✓ Staking may be needed for heavy fruiting\r\n✓ Control bacterial wilt, phomopsis blight\r\n✓ Watch for shoot and fruit borer, aphids\r\n✓ Regular picking increases yield\r\n✓ Harvest at tender stage\r\n\r\n**Expected Yield:** 25-35 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Bacterial wilt: soil-borne, fatal disease\r\n• Fruit borer: major pest, needs monitoring\r\n• Fruit drop: high temperature, water stress",
    
    "🧄 **Garlic Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 12-25°C (optimal 15-20°C)\r\n• Cool season crop for vegetative growth\r\n• Warm weather for bulb development\r\n• Tolerates light frost\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy to sandy loam soil\r\n• pH: 6.0-7.0 (ideal 6.5)\r\n• Rich in organic matter\r\n• Avoid heavy, waterlogged soils\r\n\r\n**Water Management:**\r\n• Moderate water requirement\r\n• Critical during bulb development\r\n• Stop irrigation 15-20 days before harvest\r\n• Drip irrigation ideal\r\n• Total water: 450-600mm\r\n\r\n**Planting Details:**\r\n• Season: Rabi (September-November)\r\n• Seed rate: 500-600 kg cloves/hectare\r\n• Spacing: 15cm rows, 7-10cm plants\r\n• Planting depth: 2-3cm\r\n• Growing period: 130-150 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 80-100 kg\r\n• Phosphorus: 50-60 kg\r\n• Potassium: 60-80 kg\r\n• Apply FYM 20-25 tonnes/hectare\r\n• Nitrogen in 2-3 splits\r\n\r\n**Best Practices:**\r\n✓ Use healthy, disease-free cloves\r\n✓ Treat cloves before planting\r\n✓ Maintain weed-free field\r\n✓ Control purple blotch, basal rot\r\n✓ Watch for thrips, mites\r\n✓ Harvest when leaves turn yellow-brown\r\n✓ Cure bulbs properly in shade\r\n\r\n**Expected Yield:** 12-15 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Bolting: vernalization requirements not met\r\n• Purple blotch: humid conditions\r\n• Storage rot: improper curing",
    
    "🫚 **Ginger Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 20-30°C (optimal 25-28°C)\r\n• Warm, humid tropical climate\r\n• High humidity (70-90%) preferred\r\n• Cannot tolerate frost\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy to clay loam soil\r\n• pH: 5.5-6.5 (slightly acidic)\r\n• Rich in organic matter\r\n• Good drainage absolutely essential\r\n\r\n**Water Management:**\r\n• High water requirement initially\r\n• Frequent light irrigation needed\r\n• Critical during rhizome development\r\n• Stop watering 3-4 weeks before harvest\r\n• Total water: 1500-2000mm\r\n\r\n**Planting Details:**\r\n• Season: April-June (onset of monsoon)\r\n• Seed rate: 1500-1800 kg rhizomes/hectare\r\n• Spacing: 30cm rows, 20cm plants\r\n• Planting depth: 5-7cm\r\n• Growing period: 240-270 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 60-80 kg\r\n• Phosphorus: 50-60 kg\r\n• Potassium: 80-100 kg\r\n• Apply FYM 25-30 tonnes/hectare\r\n• Split application in 3-4 doses\r\n\r\n**Best Practices:**\r\n✓ Use disease-free seed rhizomes\r\n✓ Treat rhizomes before planting\r\n✓ Mulching essential for moisture and weed control\r\n✓ Earthing up at 2-3 months\r\n✓ Control soft rot, leaf spot, rhizome rot\r\n✓ Watch for shoot borer, scale insects\r\n✓ Harvest when leaves start yellowing\r\n✓ Cure rhizomes after harvest\r\n\r\n**Expected Yield:** 20-30 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Soft rot: waterlogging, bacterial infection\r\n• Rhizome fly: major pest in some regions\r\n• Poor emergence: deep planting, low temperature",
    
    "🍇 **Grapes Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 15-40°C (optimal 23-32°C during growth)\r\n• Warm, dry climate preferred\r\n• Requires winter chilling (100-200 hours)\r\n• Dry weather during fruit ripening\r\n\r\n**Soil Requirements:**\r\n• Well-drained deep loamy to sandy loam soil\r\n• pH: 6.5-8.0 (slightly acidic to alkaline)\r\n• Deep soil (1-2m) for root penetration\r\n• Good organic matter content\r\n\r\n**Water Management:**\r\n• Critical during fruit development\r\n• Drip irrigation highly recommended\r\n• Reduce watering during ripening\r\n• Total water: 800-1200mm annually\r\n• Avoid waterlogging\r\n\r\n**Planting Details:**\r\n• Season: December-February\r\n• Spacing: 3-4m between rows, 2-3m between plants\r\n• Planting depth: Same as nursery level\r\n• Grafted plants preferred\r\n• Start bearing: 2-3 years\r\n\r\n**Fertilizer (per hectare per year):**\r\n• Nitrogen: 100-150 kg\r\n• Phosphorus: 80-120 kg\r\n• Potassium: 100-150 kg\r\n• Apply FYM 20-25 tonnes\r\n• Split into 4-5 applications\r\n\r\n**Best Practices:**\r\n✓ Regular pruning and training essential\r\n✓ Bunch thinning for quality fruits\r\n✓ Berry thinning improves size\r\n✓ Control downy mildew, powdery mildew, anthracnose\r\n✓ Watch for thrips, mealybugs, flea beetles\r\n✓ Use growth regulators (GA3) for seedless varieties\r\n✓ Harvest at proper sugar content\r\n\r\n**Expected Yield:** 20-40 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Berry drop: water stress, poor pollination\r\n• Sunburn: excessive sun exposure\r\n• Uneven ripening: irregular irrigation",
    
    "🥜 **Groundnut (Peanut) Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 20-30°C (optimal 25-30°C)\r\n• Warm season crop\r\n• Requires 100-120 frost-free days\r\n• Bright sunshine essential\r\n\r\n**Soil Requirements:**\r\n• Well-drained sandy loam to loamy soil\r\n• pH: 6.0-7.0 (ideal 6.5)\r\n• Loose soil for pod development\r\n• Calcium-rich soil preferred\r\n\r\n**Water Management:**\r\n• Critical at pegging and pod development\r\n• 4-6 irrigations typically needed\r\n• Avoid waterlogging\r\n• Stop irrigation before harvest\r\n• Total water: 500-700mm\r\n\r\n**Planting Details:**\r\n• Season: Kharif (June-July), Rabi (October-November)\r\n• Seed rate: 100-120 kg/hectare\r\n• Spacing: 30-45cm rows, 10-15cm plants\r\n• Depth: 5-6cm\r\n• Growing period: 120-140 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 20-25 kg (nitrogen-fixing)\r\n• Phosphorus: 40-60 kg\r\n• Potassium: 40-50 kg\r\n• Gypsum 400-500 kg/hectare (for calcium)\r\n• Rhizobium inoculation beneficial\r\n\r\n**Best Practices:**\r\n✓ Use certified disease-free seeds\r\n✓ Treat seeds with fungicide and Rhizobium\r\n✓ Gypsum application at flowering stage\r\n✓ Earthing up during pegging\r\n✓ Control tikka leaf spot, rust, collar rot\r\n✓ Watch for leaf miner, aphids, thrips\r\n✓ Harvest when leaves turn yellow\r\n✓ Dry pods thoroughly before storage\r\n\r\n**Expected Yield:** 20-25 quintals/hectare (pods)\r\n\r\n**Common Issues:**\r\n• Aflatoxin contamination: improper drying and storage\r\n• Poor pod filling: calcium deficiency\r\n• Empty pods: drought stress during pegging",
    
    "🍈 **Guava Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 20-35°C (optimal 25-30°C)\r\n• Tropical and subtropical climate\r\n• Tolerates wide temperature range\r\n• Can withstand light frost\r\n\r\n**Soil Requirements:**\r\n• Adapts to wide range of soils\r\n• pH: 5.5-7.5 (wide tolerance)\r\n• Deep, well-drained loamy soil ideal\r\n• Good organic matter content\r\n\r\n**Water Management:**\r\n• Regular irrigation needed\r\n• Critical during flowering and fruiting\r\n• Drip irrigation recommended\r\n• Withhold water for flower induction\r\n• Total water: 1000-1500mm annually\r\n\r\n**Planting Details:**\r\n• Season: July-August or February-March\r\n• Spacing: 5-6m between plants\r\n• Planting depth: Same as nursery level\r\n• Grafted plants preferred\r\n• Start bearing: 2-3 years\r\n\r\n**Fertilizer (per tree per year):**\r\n• Nitrogen: 500-1000g\r\n• Phosphorus: 250-500g\r\n• Potassium: 500-1000g\r\n• Apply FYM 30-40 kg per tree\r\n• Split into 3-4 applications\r\n\r\n**Best Practices:**\r\n✓ Regular pruning after harvest\r\n✓ Fruit bagging prevents fruit fly\r\n✓ Thinning improves fruit size\r\n✓ Control wilt, anthracnose, canker\r\n✓ Watch for fruit fly, mealybugs, scale insects\r\n✓ Harvest at proper maturity stage\r\n✓ Handle carefully to avoid bruising\r\n\r\n**Expected Yield:** 15-25 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Fruit fly: major pest, needs monitoring\r\n• Wilt: soil-borne fungal disease\r\n• Fruit cracking: irregular irrigation",
    
    "🌾 **Lentils Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 18-25°C (optimal 20-22°C)\r\n• Cool season crop\r\n• Tolerates light frost\r\n• Cool, dry weather for pod filling\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy to clay loam soil\r\n• pH: 6.0-7.5 (neutral preferred)\r\n• Moderate fertility adequate\r\n• Avoid waterlogged soils\r\n\r\n**Water Management:**\r\n• 1-2 irrigations sufficient\r\n• Critical at flowering and pod formation\r\n• Drought tolerant after establishment\r\n• Sensitive to waterlogging\r\n• Total water: 300-400mm\r\n\r\n**Planting Details:**\r\n• Season: Rabi (October-November)\r\n• Seed rate: 30-40 kg/hectare\r\n• Spacing: 20-30cm rows, 5-10cm plants\r\n• Depth: 4-5cm\r\n• Growing period: 110-130 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 20-25 kg (nitrogen-fixing)\r\n• Phosphorus: 40-50 kg\r\n• Potassium: 20-30 kg\r\n• Rhizobium inoculation recommended\r\n• Sulfur 20 kg if deficient\r\n\r\n**Best Practices:**\r\n✓ Use certified disease-free seeds\r\n✓ Treat seeds with fungicide and Rhizobium\r\n✓ Timely sowing crucial\r\n✓ Weed control in first 30-40 days\r\n✓ Control wilt, rust, blight\r\n✓ Watch for pod borer, aphids\r\n✓ Harvest when 80% pods turn brown\r\n✓ Thresh carefully to avoid seed damage\r\n\r\n**Expected Yield:** 10-15 quintals/hectare\r\n\r\n**Common Issues:**\r\n• Wilt: soil-borne disease in warm conditions\r\n• Rust: humid weather conditions\r\n• Poor nodulation: acidic soils",
    
    "🥬 **Lettuce Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 15-22°C (optimal 18-20°C)\r\n• Cool season crop\r\n• Sensitive to heat (causes bolting)\r\n• Tolerates light frost\r\n\r\n**Soil Requirements:**\r\n• Well-drained loamy soil\r\n• pH: 6.0-7.0 (ideal 6.5)\r\n• Rich in organic matter\r\n• Good moisture retention\r\n\r\n**Water Management:**\r\n• Consistent moisture essential\r\n• Light, frequent irrigation needed\r\n• Critical throughout growth\r\n• Drip irrigation ideal\r\n• Total water: 350-450mm\r\n\r\n**Planting Details:**\r\n• Season: Rabi (September-February)\r\n• Nursery: 20-25 day old seedlings (or direct seeding)\r\n• Spacing: 30cm rows, 25-30cm plants\r\n• Depth: 0.5-1cm (shallow)\r\n• Growing period: 60-80 days\r\n\r\n**Fertilizer (per hectare):**\r\n• Nitrogen: 80-100 kg\r\n• Phosphorus: 50-60 kg\r\n• Potassium: 50-60 kg\r\n• Apply FYM 20-25 tonnes/hectare\r\n• Nitrogen in 2-3 splits\r\n\r\n**Best Practices:**\r\n✓ Use crisp varieties for better shelf life\r\n✓ Maintain uniform moisture\r\n✓ Mulching helps temperature control\r\n✓ Control downy mildew, tip burn\r\n✓ Watch for aphids, slugs, leaf miners\r\n✓ Harvest in morning when cool\r\n✓ Cut at soil level\r\n\r\n**Expected Yield:** 15-20 tonnes/hectare\r\n\r\n**Common Issues:**\r\n• Bolting: high temperature, stress\r\n• Tip burn: calcium deficiency, irregular watering\r\n• Rib discoloration: nutrient imbalance",
    
    "🥭 **Mango Cultivation Guide:**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 24-30°C (optimal 27°C)\r\n• Tropical and subtropical climate\r\n• Requires dry weather during flowering\r\n• Sensitive to frost\r\n\r\n**Soil Requirements:**\r\n• Deep, well-drained loamy to sandy loam soil\r\n• pH: 5.5-7.5 (wide tolerance)\r\n• Deep soil (2-3m) for root development\r\n• Good organic matter content\r\n\r\n**Water Management:**\r\n• Critical during fruit development\r\n• Withhold water for flower induction\r\n• Drip irrigation recommended\r\n• Young trees need regular watering\r\n• Total water: 1000-1500mm annually\r\n\r\n**Planting Details:**\r\n• Season: July-August (monsoon)\r\n• Spacing: 8-10m between plants (varies by variety)\r\n• Planting depth: Same as nursery level\r\n• Grafted plants essential\r\n• Start bearing: 3-5 years\r\n\r\n**Fertilizer (per tree per year):**\r\n• Nitrogen: 500-1500g (age-dependent)\r\n• Phosphorus: 250-750g\r\n• Potassium: 500-1500g\r\n• Apply FYM 50-100 kg per tree\r\n• Split into 2-3 applications\r\n\r\n**Best Practices:**\r\n✓ Regular pruning for canopy management\r\n✓ Flower induction by water/nutrient stress\r\n✓ Fruit thinning for quality\r\n✓ Control anthracnose, powdery mildew, malformation\r\n✓ Watch for fruit fly, mango hopper, stem borer\r\n✓ Use ethrel for uniform ripening\r\n✓ Harvest at proper maturity\r\n\r\n**Expected Yield:** 15-25 tonnes/hectare (mature orchard)\r\n\r\n**Common Issues:**\r\n• Malformation: physiological/viral disorder\r\n• Fruit drop: various causes, normal up to extent\r\n• Spongy tissue: boron deficiency"
]

# Add new guides to the answers array
print(f"Current number of answers: {len(data['answers'])}")
data['answers'].extend(new_guides)
print(f"After adding Batch 2: {len(data['answers'])} answers")

# Add corresponding sources
for _ in range(len(new_guides)):
    data['sources'].append("AgriGuide")

# Save updated JSON
with open(json_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("✅ Batch 2 complete! Added guides for:")
print("  11. Cucumber")
print("  12. Eggplant")
print("  13. Garlic")
print("  14. Ginger")
print("  15. Grapes")
print("  16. Groundnut")
print("  17. Guava")
print("  18. Lentils")
print("  19. Lettuce")
print("  20. Mango")
