import json

# Load existing chatbot_qa_pairs.json
with open('agrisense_app/backend/chatbot_qa_pairs.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

print(f"Current number of answers: {len(data['answers'])}")

# Batch 3: Crops 21-30
batch3_guides = [
    # 21. Millet
    "🌾 **Millet Cultivation Guide**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 25-35°C optimal, highly drought-tolerant\r\n• Season: Kharif crop (June-September) in most regions\r\n• Grows well in hot, dry climates with minimal rainfall\r\n• Can tolerate poor soil conditions and water scarcity\r\n\r\n**Soil Requirements:**\r\n• Type: Well-drained sandy loam to clay loam soils\r\n• pH: 6.0-8.0 (tolerates slightly alkaline soils)\r\n• Drainage: Good drainage essential to prevent waterlogging\r\n• Organic Matter: Low to moderate (not demanding)\r\n\r\n**Water Management:**\r\n• Irrigation: Requires only 2-3 irrigations in entire season\r\n• Critical Stages: Flowering and grain filling stages\r\n• Total Water Requirement: 350-400mm for entire crop\r\n• Highly drought-resistant, ideal for rain-fed conditions\r\n\r\n**Planting Details:**\r\n• Planting Season: June-July (with monsoon onset)\r\n• Seed Rate: 8-10 kg/hectare for broadcast, 5-6 kg for line sowing\r\n• Row Spacing: 30 cm between rows, 10 cm between plants\r\n• Seed Depth: 2-3 cm\r\n• Growing Period: 70-90 days (short duration crop)\r\n\r\n**Fertilizer Requirements:**\r\n• NPK: 40:20:0 kg/hectare (low fertilizer requirement)\r\n• Apply 5-6 tonnes FYM/hectare at land preparation\r\n• Nitrogen in 2 splits: 50% basal, 50% at 30 days\r\n• Zinc sulphate 25 kg/ha if deficiency observed\r\n\r\n**Best Practices:**\r\n✓ Choose improved varieties like CO-4, GPU-28, or CO(Cu)-9\r\n✓ Practice crop rotation with legumes for soil health\r\n✓ Use seed treatment with Azospirillum for better growth\r\n✓ Maintain weed-free field during first 30 days\r\n✓ Harvest when grains are hard and moisture content is 20-25%\r\n✓ Thresh carefully to avoid grain damage\r\n✓ Store in dry conditions (moisture <12%) to prevent mold\r\n✓ Ideal crop for dryland and marginal soils\r\n\r\n**Expected Yield:**\r\n• Average: 15-20 quintals/hectare\r\n• Good Management: 25-30 quintals/hectare\r\n• Irrigated Conditions: Up to 35 quintals/hectare\r\n\r\n**Common Issues:**\r\n• Shoot Fly: Causes dead heart in young plants (use seed treatment)\r\n• Blast Disease: Fungal infection during humid conditions (resistant varieties)\r\n• Birds: Major pest during grain maturity (use bird scaring methods)",

    # 22. Mustard
    "🌻 **Mustard Cultivation Guide**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 10-25°C optimal, cool season crop\r\n• Season: Rabi crop (October-March)\r\n• Requires cool weather during vegetative growth\r\n• Warm, dry weather during maturity for quality seeds\r\n\r\n**Soil Requirements:**\r\n• Type: Well-drained loamy to clay loam soils\r\n• pH: 6.0-7.5 (slightly acidic to neutral)\r\n• Drainage: Good drainage essential, cannot tolerate waterlogging\r\n• Organic Matter: High organic content preferred\r\n\r\n**Water Management:**\r\n• Irrigation: 4-5 irrigations during entire crop season\r\n• Critical Stages: Branching, flowering, and pod formation\r\n• Total Water Requirement: 300-350mm\r\n• First irrigation at 30-35 days after sowing\r\n\r\n**Planting Details:**\r\n• Planting Season: October-November (avoid late sowing)\r\n• Seed Rate: 5-6 kg/hectare for rainfed, 3-4 kg for irrigated\r\n• Row Spacing: 30-45 cm between rows, 10-15 cm between plants\r\n• Seed Depth: 2-3 cm\r\n• Growing Period: 120-150 days depending on variety\r\n\r\n**Fertilizer Requirements:**\r\n• NPK: 60:40:40 kg/hectare for rainfed, 80:60:40 for irrigated\r\n• Apply 10 tonnes FYM/hectare 2-3 weeks before sowing\r\n• Nitrogen in 2 splits: 50% basal, 50% at 30 days\r\n• Sulphur 30-40 kg/ha crucial for oil content\r\n\r\n**Best Practices:**\r\n✓ Use certified seeds of high-yielding varieties like Pusa Bold, RH-30\r\n✓ Treat seeds with Trichoderma for disease protection\r\n✓ Practice crop rotation with cereals or pulses\r\n✓ Control aphids early with neem oil or insecticides\r\n✓ Timely weeding especially during first 30-40 days\r\n✓ Harvest when 75% pods turn yellow-brown\r\n✓ Dry pods thoroughly before threshing to avoid losses\r\n✓ Store seeds in dry conditions (moisture <8%)\r\n\r\n**Expected Yield:**\r\n• Average: 10-12 quintals/hectare\r\n• Good Management: 15-18 quintals/hectare\r\n• Irrigated with HYV: 20-25 quintals/hectare\r\n\r\n**Common Issues:**\r\n• Aphids: Suck sap from tender parts (spray neem oil or imidacloprid)\r\n• Alternaria Blight: Leaf spots and pod infection (use resistant varieties)\r\n• White Rust: White pustules on leaves (apply mancozeb fungicide)",

    # 23. Oats
    "🌾 **Oats Cultivation Guide**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 15-25°C optimal, cool season crop\r\n• Season: Rabi crop (October-March)\r\n• Tolerates cold better than most cereals\r\n• Can withstand light frost during early growth\r\n\r\n**Soil Requirements:**\r\n• Type: Well-drained loamy soils preferred\r\n• pH: 6.0-7.0 (slightly acidic to neutral)\r\n• Drainage: Requires good drainage, sensitive to waterlogging\r\n• Organic Matter: Moderate to high for best results\r\n\r\n**Water Management:**\r\n• Irrigation: 4-5 irrigations during crop period\r\n• Critical Stages: Crown root initiation, tillering, flowering, grain filling\r\n• Total Water Requirement: 350-400mm\r\n• First irrigation at 20-25 days after sowing\r\n\r\n**Planting Details:**\r\n• Planting Season: October-November for grain, September for fodder\r\n• Seed Rate: 80-100 kg/hectare (higher rate for fodder)\r\n• Row Spacing: 20-25 cm between rows for grain, broadcast for fodder\r\n• Seed Depth: 4-5 cm\r\n• Growing Period: 110-140 days for grain, 60-70 days for fodder\r\n\r\n**Fertilizer Requirements:**\r\n• NPK: 80:40:40 kg/hectare for grain, 100:50:50 for fodder\r\n• Apply 8-10 tonnes FYM/hectare before sowing\r\n• Nitrogen in 2 splits: 50% basal, 50% at first irrigation\r\n• Additional nitrogen for fodder production\r\n\r\n**Best Practices:**\r\n✓ Select varieties based on purpose (grain vs fodder)\r\n✓ Use certified seeds treated with fungicides\r\n✓ Ensure good seed-soil contact during sowing\r\n✓ Control weeds during first 30-40 days\r\n✓ For fodder, cut at 50% flowering stage\r\n✓ For grain, harvest when moisture content is 20-25%\r\n✓ Dry grain properly before storage (12% moisture)\r\n✓ Can be used in crop rotation with legumes\r\n\r\n**Expected Yield:**\r\n• Grain: 20-25 quintals/hectare (average)\r\n• Grain: 30-35 quintals/hectare (good management)\r\n• Fodder: 250-300 quintals/hectare green weight\r\n\r\n**Common Issues:**\r\n• Rust Diseases: Yellow or brown pustules on leaves (use resistant varieties)\r\n• Smut: Grain replacement with black spores (seed treatment essential)\r\n• Aphids: Suck sap from leaves and stems (control with insecticides)",

    # 24. Orange
    "🍊 **Orange Cultivation Guide**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 13-37°C range, 25-35°C optimal for growth\r\n• Season: Perennial crop, main flowering in February-March\r\n• Requires warm, humid climate with good sunlight\r\n• Sensitive to frost, avoid areas with temperatures below 0°C\r\n\r\n**Soil Requirements:**\r\n• Type: Well-drained sandy loam to clay loam soils\r\n• pH: 5.5-7.5 (slightly acidic to neutral preferred)\r\n• Drainage: Excellent drainage critical to prevent root rot\r\n• Organic Matter: High organic content beneficial\r\n\r\n**Water Management:**\r\n• Irrigation: Weekly during dry season, reduce during monsoon\r\n• Critical Stages: Flowering, fruit development, fruit enlargement\r\n• Total Water Requirement: 1000-1200mm annually\r\n• Drip irrigation most efficient for citrus orchards\r\n\r\n**Planting Details:**\r\n• Planting Season: July-August (with monsoon) or February-March\r\n• Plant Spacing: 5m x 5m or 6m x 6m (high-density: 4m x 4m)\r\n• Pit Size: 60cm x 60cm x 60cm, filled with FYM and topsoil\r\n• Grafted Saplings: Use 1-year-old budded plants\r\n• Bearing Period: Starts from 3-4 years, full bearing at 7-8 years\r\n\r\n**Fertilizer Requirements:**\r\n• NPK: 500:250:500 g/tree/year for young trees (1-3 years)\r\n• Bearing Trees: 1000:500:1000 g/tree/year\r\n• Apply 20-25 kg FYM/tree annually in 2 splits\r\n• Micronutrients: Zinc, iron, manganese foliar sprays\r\n• Split application: 3 times (Feb-Mar, Jun-Jul, Oct-Nov)\r\n\r\n**Best Practices:**\r\n✓ Use disease-free grafted saplings from certified nurseries\r\n✓ Maintain proper spacing for air circulation and sunlight\r\n✓ Regular pruning to remove dead, diseased, or crossing branches\r\n✓ Mulch around tree base to conserve moisture\r\n✓ Control citrus psylla to prevent greening disease\r\n✓ Monitor for nutrient deficiencies (yellowing leaves)\r\n✓ Harvest fruits when fully colored but firm\r\n✓ Use integrated pest management for pest control\r\n\r\n**Expected Yield:**\r\n• Young Trees (3-5 years): 20-30 kg/tree\r\n• Mature Trees (7-10 years): 80-120 kg/tree\r\n• Full Bearing: 150-200 kg/tree (400-600 fruits)\r\n\r\n**Common Issues:**\r\n• Citrus Canker: Bacterial disease causing lesions (remove infected parts)\r\n• Citrus Greening: Yellowing and stunted growth (control psylla vectors)\r\n• Fruit Fly: Maggots in fruits (use fruit fly traps and bait sprays)",

    # 25. Papaya
    "🥭 **Papaya Cultivation Guide**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 20-35°C optimal, frost-sensitive\r\n• Season: Year-round planting possible in tropical regions\r\n• Requires warm, humid climate with good sunlight\r\n• Cannot tolerate waterlogging or strong winds\r\n\r\n**Soil Requirements:**\r\n• Type: Well-drained sandy loam to loamy soils\r\n• pH: 6.0-7.0 (slightly acidic to neutral)\r\n• Drainage: Excellent drainage essential, raised beds recommended\r\n• Organic Matter: High organic content for best growth\r\n\r\n**Water Management:**\r\n• Irrigation: Frequent light irrigation, avoid waterlogging\r\n• Critical Stages: Flowering, fruit development, throughout growth\r\n• Total Water Requirement: 1500-2000mm annually\r\n• Drip irrigation recommended for efficient water use\r\n\r\n**Planting Details:**\r\n• Planting Season: February-March or June-July best\r\n• Plant Spacing: 2m x 2m or 2.5m x 2.5m\r\n• Pit Size: 45cm x 45cm x 45cm filled with FYM and topsoil\r\n• Seed/Seedling: Use healthy seedlings or hybrid seeds\r\n• Bearing Period: Starts flowering at 4-5 months, fruiting at 6-8 months\r\n\r\n**Fertilizer Requirements:**\r\n• NPK: 200:200:400 g/plant/year in young stage\r\n• Bearing Plants: 300:250:500 g/plant/year\r\n• Apply 10-15 kg FYM/plant annually\r\n• Monthly application of fertilizers during growing season\r\n• Micronutrients: Zinc and boron foliar sprays\r\n\r\n**Best Practices:**\r\n✓ Use improved hybrid varieties like Red Lady, Taiwan Red\r\n✓ Maintain 1-2 female/hermaphrodite plants per pit\r\n✓ Provide support to prevent wind damage\r\n✓ Mulch around plants to conserve moisture\r\n✓ Remove male plants after sex identification (2-3 months)\r\n✓ Regular inspection for papaya ring spot virus\r\n✓ Harvest when fruits show yellow streaks (3/4 ripe)\r\n✓ De-sap fruits immediately after harvest for better quality\r\n\r\n**Expected Yield:**\r\n• First Year: 30-40 kg/plant\r\n• Second Year: 50-70 kg/plant\r\n• Per Hectare: 60-80 tonnes with good management\r\n\r\n**Common Issues:**\r\n• Papaya Ring Spot Virus: Mosaic patterns on leaves (remove infected plants)\r\n• Powdery Mildew: White powder on leaves (apply sulfur fungicides)\r\n• Fruit Fly: Maggots in fruits (use fruit fly traps and cover fruits)",

    # 26. Peas
    "🫛 **Peas Cultivation Guide**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 10-20°C optimal, cool season crop\r\n• Season: Rabi crop (October-February)\r\n• Requires cool weather during vegetative and flowering stages\r\n• High temperatures reduce yield and quality\r\n\r\n**Soil Requirements:**\r\n• Type: Well-drained loamy to clay loam soils\r\n• pH: 6.0-7.5 (slightly acidic to neutral)\r\n• Drainage: Good drainage essential, avoid waterlogged areas\r\n• Organic Matter: Moderate to high for better nodulation\r\n\r\n**Water Management:**\r\n• Irrigation: 4-6 irrigations during crop period\r\n• Critical Stages: Flowering and pod development\r\n• Total Water Requirement: 300-350mm\r\n• Avoid excess water which promotes vegetative growth\r\n\r\n**Planting Details:**\r\n• Planting Season: October-November in plains, February-March in hills\r\n• Seed Rate: 80-100 kg/hectare for garden peas, 40-50 kg for field peas\r\n• Row Spacing: 30-45 cm between rows, 5-10 cm between plants\r\n• Seed Depth: 4-5 cm\r\n• Growing Period: 60-90 days for garden peas, 120-150 days for field peas\r\n\r\n**Fertilizer Requirements:**\r\n• NPK: 20:60:40 kg/hectare (low nitrogen due to nitrogen fixation)\r\n• Apply 8-10 tonnes FYM/hectare before sowing\r\n• All fertilizers as basal dose at sowing\r\n• Rhizobium culture seed treatment for better nodulation\r\n\r\n**Best Practices:**\r\n✓ Use certified seeds of disease-resistant varieties\r\n✓ Treat seeds with Rhizobium and fungicide\r\n✓ Sow at optimal time to avoid heat stress\r\n✓ Provide support for tall varieties (staking)\r\n✓ Control weeds during first 30-40 days\r\n✓ Harvest green pods when tender and fully developed\r\n✓ Multiple pickings at 3-4 day intervals\r\n✓ Practice crop rotation with cereals\r\n\r\n**Expected Yield:**\r\n• Garden Peas (green): 80-100 quintals/hectare\r\n• Garden Peas (good management): 120-150 quintals/hectare\r\n• Field Peas (dry seeds): 15-20 quintals/hectare\r\n\r\n**Common Issues:**\r\n• Powdery Mildew: White powder on leaves and pods (apply sulfur fungicides)\r\n• Pod Borer: Larvae bore into pods (use biological control or insecticides)\r\n• Wilt Disease: Yellowing and wilting (use resistant varieties and crop rotation)",

    # 27. Pepper (Bell Pepper/Capsicum)
    "🫑 **Pepper (Bell Pepper) Cultivation Guide**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 20-30°C optimal, sensitive to extremes\r\n• Season: Year-round in protected cultivation, October-February in open field\r\n• Requires moderate temperatures and humidity\r\n• Sensitive to frost and high rainfall during fruiting\r\n\r\n**Soil Requirements:**\r\n• Type: Well-drained sandy loam to clay loam soils\r\n• pH: 6.0-7.0 (slightly acidic to neutral)\r\n• Drainage: Excellent drainage crucial, raised beds recommended\r\n• Organic Matter: High organic content essential\r\n\r\n**Water Management:**\r\n• Irrigation: Frequent light irrigation, keep soil consistently moist\r\n• Critical Stages: Transplanting, flowering, fruit development\r\n• Total Water Requirement: 600-800mm\r\n• Drip irrigation ideal for consistent moisture\r\n\r\n**Planting Details:**\r\n• Nursery Season: July-August for winter crop, January-February for summer\r\n• Transplanting: 4-5 weeks after sowing when 4-5 leaves appear\r\n• Plant Spacing: 60cm x 45cm or 75cm x 45cm\r\n• Seedling Depth: Plant at same depth as in nursery\r\n• Growing Period: 60-70 days from transplanting to first harvest\r\n\r\n**Fertilizer Requirements:**\r\n• NPK: 150:100:100 kg/hectare\r\n• Apply 20-25 tonnes FYM/hectare before transplanting\r\n• Nitrogen in 3 splits: 50% basal, 25% at 30 days, 25% at 60 days\r\n• Calcium and magnesium important for fruit quality\r\n\r\n**Best Practices:**\r\n✓ Use healthy seedlings from disease-free nursery\r\n✓ Transplant in evening hours to reduce shock\r\n✓ Mulch with plastic or organic materials\r\n✓ Provide staking support to prevent lodging\r\n✓ Remove first few flowers for better plant establishment\r\n✓ Control thrips and aphids early\r\n✓ Harvest when fruits reach full size and desired color\r\n✓ Regular picking encourages more fruiting\r\n\r\n**Expected Yield:**\r\n• Open Field: 200-250 quintals/hectare\r\n• Good Management: 300-350 quintals/hectare\r\n• Protected Cultivation: 500-700 quintals/hectare\r\n\r\n**Common Issues:**\r\n• Bacterial Wilt: Sudden wilting of plants (crop rotation and resistant varieties)\r\n• Thrips: Damage to flowers and fruits (use yellow sticky traps)\r\n• Blossom End Rot: Calcium deficiency causing dark spots (maintain soil moisture)",

    # 28. Pomegranate
    "🍎 **Pomegranate Cultivation Guide**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 15-38°C range, 35-38°C ideal for fruit development\r\n• Season: Perennial, flowering twice (Feb-Mar and Aug-Sep)\r\n• Requires hot, dry climate during fruiting\r\n• Can tolerate semi-arid conditions better than most fruits\r\n\r\n**Soil Requirements:**\r\n• Type: Well-drained sandy loam to loamy soils preferred\r\n• pH: 5.5-7.5 (slightly acidic to neutral)\r\n• Drainage: Excellent drainage mandatory, avoid heavy soils\r\n• Organic Matter: Moderate levels, tolerates poor soils\r\n\r\n**Water Management:**\r\n• Irrigation: Weekly during summer, fortnightly in winter\r\n• Critical Stages: Flowering, fruit set, fruit development\r\n• Total Water Requirement: 800-1000mm annually\r\n• Drip irrigation most suitable for commercial orchards\r\n\r\n**Planting Details:**\r\n• Planting Season: July-August (monsoon) or February-March\r\n• Plant Spacing: 4m x 4m or 5m x 5m (high-density: 3m x 3m)\r\n• Pit Size: 60cm x 60cm x 60cm filled with FYM and topsoil\r\n• Planting Material: Use hardwood cuttings or air-layered plants\r\n• Bearing Period: Starts from 2-3 years, full bearing at 5-6 years\r\n\r\n**Fertilizer Requirements:**\r\n• NPK: Young Trees (1-3 years): 100:50:50 g/tree/year\r\n• Bearing Trees: 500:250:250 g/tree/year\r\n• Apply 15-20 kg FYM/tree annually\r\n• Split application in 2-3 doses (Feb-Mar, Jun-Jul, Oct-Nov)\r\n• Micronutrients: Zinc and iron foliar applications\r\n\r\n**Best Practices:**\r\n✓ Use superior varieties like Bhagwa, Ganesh, Arakta\r\n✓ Regular pruning to maintain plant height and shape\r\n✓ Remove suckers and water sprouts regularly\r\n✓ Bahar treatment to synchronize flowering (withhold water, then irrigate)\r\n✓ Hand pollination for better fruit set if needed\r\n✓ Fruit thinning to improve fruit size and quality\r\n✓ Harvest when fruits fully colored and make metallic sound when tapped\r\n✓ Control bacterial blight with copper sprays\r\n\r\n**Expected Yield:**\r\n• Young Trees (3-5 years): 8-10 kg/tree\r\n• Mature Trees (5-10 years): 25-40 kg/tree\r\n• Full Bearing: 50-70 kg/tree per year\r\n\r\n**Common Issues:**\r\n• Bacterial Blight: Black spots on leaves and fruits (copper sprays)\r\n• Fruit Borer: Larvae bore into fruits (pheromone traps and insecticides)\r\n• Fruit Cracking: Irregular irrigation (maintain consistent moisture)",

    # 29. Pumpkin
    "🎃 **Pumpkin Cultivation Guide**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 18-35°C optimal, warm season crop\r\n• Season: Summer (Feb-Mar) and Rainy (Jun-Jul) seasons\r\n• Requires warm weather and plenty of sunshine\r\n• Sensitive to frost, cannot tolerate waterlogging\r\n\r\n**Soil Requirements:**\r\n• Type: Well-drained sandy loam to loamy soils\r\n• pH: 6.0-7.0 (slightly acidic to neutral)\r\n• Drainage: Good drainage essential to prevent root rot\r\n• Organic Matter: High organic content for vigorous growth\r\n\r\n**Water Management:**\r\n• Irrigation: Regular irrigation to maintain soil moisture\r\n• Critical Stages: Vine growth, flowering, fruit development\r\n• Total Water Requirement: 500-600mm\r\n• Reduce irrigation near maturity to improve fruit quality\r\n\r\n**Planting Details:**\r\n• Planting Season: February-March (summer) or June-July (rainy)\r\n• Seed Rate: 4-5 kg/hectare for direct sowing\r\n• Row Spacing: 2.5-3m between rows, 60-90cm between plants\r\n• Seed Depth: 2-3 cm, 2-3 seeds per hill\r\n• Growing Period: 90-120 days from sowing to harvest\r\n\r\n**Fertilizer Requirements:**\r\n• NPK: 60:60:40 kg/hectare\r\n• Apply 20-25 tonnes FYM/hectare before sowing\r\n• Nitrogen in 2 splits: 50% basal, 50% at flowering\r\n• Phosphorus and potassium as basal dose\r\n\r\n**Best Practices:**\r\n✓ Use certified seeds of hybrid varieties for better yield\r\n✓ Prepare raised beds or ridges for good drainage\r\n✓ Mulch around plants to conserve moisture\r\n✓ Train vines on trellises for better space utilization\r\n✓ Hand pollination in early morning for better fruit set\r\n✓ Remove diseased leaves and fruits promptly\r\n✓ Harvest when fruits fully mature and rind hardens\r\n✓ Leave 2-3 cm stalk attached during harvest\r\n\r\n**Expected Yield:**\r\n• Average: 200-250 quintals/hectare\r\n• Good Management: 300-400 quintals/hectare\r\n• Hybrid Varieties: Up to 500 quintals/hectare\r\n\r\n**Common Issues:**\r\n• Powdery Mildew: White powder on leaves (apply sulfur or wettable sulfur)\r\n• Fruit Fly: Maggots in fruits (use fruit fly traps and bait sprays)\r\n• Downy Mildew: Yellow spots on leaves (apply mancozeb fungicide)",

    # 30. Radish
    "🥕 **Radish Cultivation Guide**\r\n\r\n**Climate Requirements:**\r\n• Temperature: 10-25°C optimal, cool season crop\r\n• Season: Year-round cultivation possible, best in winter (Oct-Feb)\r\n• Prefers cool weather for quality root development\r\n• High temperatures cause pungency and woody roots\r\n\r\n**Soil Requirements:**\r\n• Type: Well-drained sandy loam to loamy soils\r\n• pH: 6.0-7.0 (slightly acidic to neutral)\r\n• Drainage: Good drainage essential for quality roots\r\n• Organic Matter: High organic content for tender roots\r\n\r\n**Water Management:**\r\n• Irrigation: Frequent light irrigation to maintain consistent moisture\r\n• Critical Stages: Throughout growth, especially root enlargement\r\n• Total Water Requirement: 250-300mm\r\n• Irregular irrigation causes root cracking\r\n\r\n**Planting Details:**\r\n• Planting Season: September-February (main season)\r\n• Seed Rate: 8-10 kg/hectare for direct sowing\r\n• Row Spacing: 20-30 cm between rows, 5-8 cm between plants\r\n• Seed Depth: 1.5-2 cm\r\n• Growing Period: 25-60 days depending on variety\r\n\r\n**Fertilizer Requirements:**\r\n• NPK: 50:50:50 kg/hectare\r\n• Apply 15-20 tonnes FYM/hectare before sowing\r\n• All fertilizers as basal dose at sowing\r\n• Avoid excess nitrogen which promotes leaf growth over roots\r\n\r\n**Best Practices:**\r\n✓ Use fresh seeds for better germination\r\n✓ Ensure fine tilth for uniform root development\r\n✓ Thin seedlings to proper spacing within 10-15 days\r\n✓ Maintain consistent soil moisture throughout\r\n✓ Control weeds early to reduce competition\r\n✓ Harvest when roots reach marketable size (don't delay)\r\n✓ Multiple sowings for continuous supply\r\n✓ Practice crop rotation with non-crucifers\r\n\r\n**Expected Yield:**\r\n• European Varieties: 200-250 quintals/hectare\r\n• Asiatic Varieties: 300-400 quintals/hectare\r\n• Good Management: Up to 500 quintals/hectare\r\n\r\n**Common Issues:**\r\n• Root Maggots: Larvae damage roots (use seed treatment and crop rotation)\r\n• Flea Beetles: Small holes in leaves (use neem oil or insecticides)\r\n• Root Cracking: Irregular irrigation (maintain consistent moisture)"
]

# Add to answers
data['answers'].extend(batch3_guides)

# Add corresponding sources
batch3_sources = ["AgriGuide"] * len(batch3_guides)
data['sources'].extend(batch3_sources)

print(f"After adding Batch 3: {len(data['answers'])} answers")

# Save updated data
with open('agrisense_app/backend/chatbot_qa_pairs.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("\n✅ Batch 3 complete! Added guides for:")
crops_batch3 = [
    "21. Millet",
    "22. Mustard", 
    "23. Oats",
    "24. Orange",
    "25. Papaya",
    "26. Peas",
    "27. Pepper (Bell Pepper)",
    "28. Pomegranate",
    "29. Pumpkin",
    "30. Radish"
]
for crop in crops_batch3:
    print(f"   • {crop}")

print("\nProgress: 38/48 crops now have detailed cultivation guides! 📊")
print("Ready for Batch 4 (final 10 crops) when you're ready! 🚀")
